# Google Discovery Document Tracker Configuration

# Storage settings
storage_path: "./data/storage"
log_path: "./data/changes"

# Check interval in seconds
check_interval: 3600  # 1 hour

# Discord webhook config (optional)
enable_discord_webhooks: false
discord_webhook_config:
  tracker_api_url: https://example.com
  # All errors can be sent to this dedicated webhook URL (optional)
  error_webhook_url: https://discord.com/api/webhooks/errors/redacted
  # Role ID to mention when errors occur (optional)
  error_mention_role_id: 1315221800000000000 # change this to your error role ID
  tag_mention_role_ids:
    - tag: new_method
      role_id: 1315221536483053590 # change this
    - tag: removed_method
      role_id: 1315221680242688052 # change this
  services:
    - service: "staging-people-pa.sandbox.googleapis.com"
      name: Internal People API (Staging)
      webhook_url: https://discord.com/api/webhooks/redacted # change this
    - service: "staging-youtube.sandbox.googleapis.com"
      name: YouTube Data API v3 (Stage)
      webhook_url: https://discord.com/api/webhooks/redacted # change this

# Services to track
services:    
  - service: "people-pa.googleapis.com"
  
  - service: "staging-youtube.sandbox.googleapis.com"
    key: "AIzaSyCG_6Rm6c7ucLr2NwAq33-vluCp2VfSkf0"